#ifndef BOARD_H
#define BOARD_H

#include <driverlib.h>

#define VCCINT_EN_PORT GPIO_PORT_P1
#define VCCINT_EN_PIN GPIO_PIN1
#define VCC_1V8_EN_PORT GPIO_PORT_P1
#define VCC_1V8_EN_PIN GPIO_PIN6
#define VCC_2V5_EN_PORT GPIO_PORT_P1
#define VCC_2V5_EN_PIN GPIO_PIN3
#define VCC_3V3_EN_PORT GPIO_PORT_P1
#define VCC_3V3_EN_PIN GPIO_PIN5

#define VCCINT_PGOOD_PORT GPIO_PORT_P1
#define VCCINT_PGOOD_PIN GPIO_PIN0
#define VCC_1V8_PGOOD_PORT GPIO_PORT_P1
#define VCC_1V8_PGOOD_PIN GPIO_PIN7
#define VCC_2V5_PGOOD_PORT GPIO_PORT_P1
#define VCC_2V5_PGOOD_PIN GPIO_PIN2
#define VCC_3V3_PGOOD_PORT GPIO_PORT_P1
#define VCC_3V3_PGOOD_PIN GPIO_PIN4

#define BACKLIGHT_EN_PORT GPIO_PORT_P2
#define BACKLIGHT_EN_PIN GPIO_PIN0
#define LCD_EN_PORT GPIO_PORT_P3
#define LCD_EN_PIN GPIO_PIN5
#define SCALER_RESET_PORT GPIO_PORT_P2
#define SCALER_RESET_PIN GPIO_PIN4
#define SCALER_BACKLIGHT_PORT GPIO_PORT_P4
#define SCALER_BACKLIGHT_PIN GPIO_PIN2
#define SCALER_DOS_ASPECT_PORT GPIO_PORT_P2
#define SCALER_DOS_ASPECT_PIN GPIO_PIN6

#define MXM_POWER_GOOD_PORT GPIO_PORT_P2
#define MXM_POWER_GOOD_PIN GPIO_PIN2
#define MXM_POWER_ENABLE_PORT GPIO_PORT_P3
#define MXM_POWER_ENABLE_PIN GPIO_PIN0
#define MXM_OVERT_PORT GPIO_PORT_P3
#define MXM_OVERT_PIN GPIO_PIN3
#define FAN_PWM_PORT GPIO_PORT_P3
#define FAN_PWM_PIN GPIO_PIN1
#define VSA_BLANK_FIX_PORT GPIO_PORT_P2
#define VSA_BLANK_FIX_PIN GPIO_PIN3

#define FB_D3_PORT GPIO_PORT_P2
#define FB_D3_PIN GPIO_PIN1
#define FB_D2_PORT GPIO_PORT_P3
#define FB_D2_PIN GPIO_PIN4
#define PCI_RESET_PORT GPIO_PORT_P2
#define PCI_RESET_PIN GPIO_PIN7

#define HOST_CLOCK_PORT GPIO_PORT_P4
#define HOST_CLOCK_PIN GPIO_PIN1
#define HOST_DATA_IN_PORT GPIO_PORT_P4
#define HOST_DATA_IN_PIN GPIO_PIN0
#define HOST_DATA_OUT_PORT GPIO_PORT_P3
#define HOST_DATA_OUT_PIN GPIO_PIN7

#define GPIO_HIGH(signal) \
	GPIO_setOutputHighOnPin(signal##_PORT, signal##_PIN)
#define GPIO_LOW(signal) \
	GPIO_setOutputLowOnPin(signal##_PORT, signal##_PIN)
#define GPIO_READ(signal) \
	GPIO_getInputPinValue(signal##_PORT, signal##_PIN)

#endif
