#ifndef FIRMWARE_CONFIG_H
#define FIRMWARE_CONFIG_H

#define MCLK_FREQ_MHZ 16

#define BACKLIGHT_ENABLE_DELAY_MS 500
#define PRE_VCORE_DELAY_LEGACY_UNITS 5000
#define PRE_BRIDGE_DELAY_LEGACY_UNITS 10000

#define ENABLE_SCALER_BACKLIGHT_GATE 1
#define FAN_STARTUP_DELAY_TICKS 131070UL
/* backlight PWM prescale: run it every Nth Timer0 ISR so its 10% on-pulse is
 * N ISR periods (~240 us at 32) instead of one (~7.5 us), immune to jitter.
 * The fan keeps the full ISR rate. */
#define BACKLIGHT_PWM_PRESCALE 32

#define TMP103_VARIANT_A 0
#define TMP103_VARIANT_B 1
#define TMP103_VARIANT_C 2
#define TMP103_VARIANT TMP103_VARIANT_B

#define OVERTEMP_SHUTDOWN_C 90
#define EXTERNAL_TEMP_INVALID_MIN 201

#define SOFT_I2C_DELAY_CYCLES 160

#define HOST_PACKET_TIMEOUT_TICKS 2
#define HOST_TIMEOUT_COUNTER_LIMIT 10

#endif
